# Generated by Django 2.2.10 on 2020-06-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0002_auto_20200108_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_size',
            field=models.IntegerField(default=0),
        ),
    ]
