stages:
  - build
  - clean
  - deploy

build:
  stage: build
  tags:
    - net640
  script:
    - cd /home/gitlab-runner/net640kb && git pull
    - cd /home/gitlab-runner/net640kb && docker-compose  -f docker-compose.yml build --no-cache
  when: always

deploy:
  stage: deploy
  tags:
    - net640
  script:
    - cd /home/gitlab-runner/net640kb && docker-compose -f docker-compose.yml down
    - cd /home/gitlab-runner/net640kb && docker-compose -f docker-compose.yml up -d
  when: on_success
