version: '2.0'

volumes:
  postgres_data:
services:
  db:
    image: postgres
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
  web:
    build:
         context: .
         dockerfile: ./docker/web_service/Dockerfile
    command: /app/docker/web_service/fire.sh
    volumes:
    - static-content:/app/static/
    - media-content:/app/media/
    - logs-app:/app/logs
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
      - redis

  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080

    ports: 
      - "80:8080"
    depends_on:
          - web
    volumes:
      - static-content:/app/static
      - media-content:/app/media
      - logs-app:/srv/www/net640/logs
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/uwsgi_config/:/srv/config

volumes:
    static-content:
    media-content:
    logs-app:
