version: '2.0'

services:
  baseweb:
    build:
         context: .
         dockerfile: ./docker/web_service/Dockerfile-develop
    environment:
       - SECRET_KEY=${SECRET_KEY}
       - DATABASE_PASSWORD=${DATABASE_PASSWORD}
       - DATABASE_USER=${DATABASE_USER}
       - DATABASE_NAME=${DATABASE_NAME}
       - DATABASE_HOST=${DATABASE_HOST}
       - REDIS_HOST=${REDIS_HOST}
       - REDIS_PORT=${REDIS_PORT}
       - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
       - EMAIL_HOST_USER=${EMAIL_HOST_USER}
       - EMAIL_HOST=${EMAIL_HOST}
       - DEPLOY_ENV=${DEPLOY_ENV}
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
  user_cache:
    restart: always
    image: redis
    expose:
      - "6379"
  web:
    extends: baseweb
    command: /app/docker/web_service/start_uwsgi.sh
    volumes:
    - ./Net640/apps:/app/Net640/apps
    - ${LOGS}/django:/app/logs/django
    - static-content:/app/static/
    - media-content:/app/media/
    depends_on:
      - db
      - redis

  daphne:
    extends: baseweb
    command: /app/docker/web_service/start_daphne.sh
    volumes:
    - ./Net640/apps:/app/Net640/apps
    - ${LOGS}/daphne:/app/logs/django/
    depends_on:
      - db
      - redis
  nginx:
    restart: always
    image: nginx:latest
    ports: 
      - "8080:8080"
    depends_on:
          - web
    volumes:
      - static-content:/app/static
      - media-content:/app/media
      - ${LOGS}/nginx:/var/www/logs
      - ./docker/nginx_develop/:/etc/nginx/conf.d
      - ./docker/uwsgi_config/:/srv/config

  selenium:
    image: selenium/standalone-firefox-debug
    ports:
      - 4444:4444   # Selenium
      - 5900:5900   # VNC server, password is secret

volumes:
    static-content:
    media-content:
