# Generated by Django 2.2.8 on 2020-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresetpassword',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='UserConfirmationCode',
        ),
        migrations.DeleteModel(
            name='UserResetPassword',
        ),
    ]
