# Generated by Django 2.2.10 on 2020-07-02 08:45

import Net640.apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_custom_pgsql_get_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=Net640.apps.images.models.user_avatar_path),
        ),
    ]
