from python:3.7

COPY requirements.txt /tmp/

RUN apt-get update
RUN apt-get install -y python3-dev git vim mc

RUN pip install -r /tmp/requirements.txt
RUN pip install channels==2.2.0
RUN pip install channels-redis==2.4.0
